---
title: "Interactive Penguins"
author: "Deanna Elliott"
date: "10/19/2021"
output: html_document
---

```{r setup, include=FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = TRUE)

#install and attach necessary packages

library(tidyverse)
library(DT)
library(plotly)
library(palmerpenguins)
library(here)
```

## Plots ##
Create interactive scatterplot of penguin flipper length (x) vs body mass (y), with points having different colors based on species

```{r plotly}

penguins_graph <- ggplot(data = penguins,
       aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_jitter(aes(color = species))

ggplotly(penguins_graph)
```

Create an interactive table of the penguins data using {DT}

```{r DT}

datatable(penguins)
```

Create a column graph (using geom_bar) of counts of penguins by island, with fill color indicating species. Then save with ggsave.

```{r}

ggplot(data = penguins,
       aes(x = island)) +
  geom_bar(aes(fill = species))

ggsave(here("final_figures", "island_counts.png"))
```

